site:
  title: "菇言菇语"
  favicon: "http://img.ma5hr00m.top/main/emoticon/favicon-64.ico"
  description: "Usami Kinoko's Website."
  author: "Usami Kinoko"

links:
  - href: "https://github.com/ma5hr00m"
    icon: "<SiGithub className='text-7' />"
  - href: "https://x.com/ma5hr00m"
    icon: "<FaXTwitter className='text-7' />"
  - href: "https://juejin.cn/user/811865333304430"
    icon: "<SiJuejin className='text-7' />"
  - href: "/articles"
    icon: "<PiArticleMediumFill className='text-7' />"
  - href: "/animation"
    icon: "<BsSkipStartBtnFill className='text-7' />"
  - href: "/gallery"
    icon: "<IoImagesSharp className='text-7' />"