name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }} \
            --build-arg ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }} \
            --build-arg ENDPOINT=${{ secrets.OSS_ENDPOINT }} \
            --build-arg BUCKET_NAME=${{ secrets.OSS_BUCKET_NAME }} \
            --build-arg OAUTH_GITHUB_TOKEN=${{ secrets.OAUTH_GITHUB_TOKEN }} \
            --build-arg APP_PORT=${{ secrets.APP_PORT }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:${{ github.sha }} .

          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_EMAIL }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:${{ github.sha }}
            docker stop focalhub || true  
            docker rm focalhub || true   
            docker run -d --name focalhub -p 2050:2050 ${{ secrets.DOCKER_HUB_USERNAME }}/focalhub:${{ github.sha }}
            sudo sysctl -w net.ipv4.ip_forward=1
