name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t username/focalhub:${{ github.sha }} .
          docker tag username/focalhub:${{ github.sha }} username/focalhub:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_EMAIL }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push username/focalhub:latest
          docker push username/focalhub:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull username/focalhub:${{ github.sha }}
            docker stop focalhub || true  
            docker rm focalhub || true   
            docker run -d --name focalhub -p 2050:2050 username/focalhub:${{ github.sha }}
